[package]
name = "halo2-rsa"
version = "0.1.0"
edition = "2021"
authors = ["Sora Suegami"]
description = "RSA verification circuit in halo2."
license = "MIT"

[lib]

[dependencies]
maingate =  { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0", rev = "ed953b054b906b64787dc9a8cbefc0db4be9f8fa"}
halo2wrong =   { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0", rev = "ed953b054b906b64787dc9a8cbefc0db4be9f8fa"}
halo2_gadgets = { git = "https://github.com/privacy-scaling-explorations/halo2.git", version = "0.2.0", rev = "a9e99a72a65d7c98e8a4258c2c94269c834d1c10", features = ["unstable"]}
num-bigint = { version = "0.4", features = ["rand"] }

[dev-dependencies]
rand = "0.8.5"
