[package]
name = "halo2_rsa"
version = "0.1.0"
edition = "2021"
authors = ["Sora Suegami"]
description = "RSA verification circuit in halo2."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maingate =  { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0"}
halo2wrong =   { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0"}
num-bigint = { version = "0.4", features = ["rand"] }

[dev-dependencies]
rand = "0.8.5"
