[package]
name = "halo2-rsa"
version = "0.1.0"
edition = "2021"
authors = ["Sora Suegami"]
description = "RSA verification circuit in halo2."
license = "MIT"

[lib]

[dependencies]
maingate =  { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0", rev = "56639b615295e08e0ef145d8a0c3876f606a7c5c"}
halo2wrong =   { git = "https://github.com/privacy-scaling-explorations/halo2wrong", version = "0.1.0", rev = "56639b615295e08e0ef145d8a0c3876f606a7c5c"}
num-bigint = { version = "0.4", features = ["rand"] }

[dev-dependencies]
rand = "0.8.5"
